### PR TITLE
Add support for disk conversion

### PR DESCRIPTION
**Pull request by bennyz**
This PR adds support for disk conversion, engine uses the copy_data verb to perform this operation and the changes include:
* Support for working with illegal volumes
* Support for copying volumes within the same image
* Support for a sequence number in volumes

### CODE REVIEW

**Comment by bennyz** [comment]
@nirs @vjuranek

**Review by vjuranek — APPROVED** [review]

**Review by nirs — CHANGES_REQUESTED** [review]
commit fe141180abaf7883fd3afbc986ee0edbb9117b33 

    storage: add sequence field to volumemetadata

Has many failed tests:
https://github.com/nirs/vdsm/runs/4761767384?check_suite_focus=true

But there are no failed tests with next commit. This means some changes in the tests or code
need to move the the previous commit.

Please resolve this issue and post a link to working test run for this commit.

**Comment by nirs** [comment]
@bennyz The first 3 commits looks ready, we can merge them now if you remove the last commit from the PR and post them later when they are ready.

**Comment by bennyz** [comment]
Closing in favor of:
https://github.com/oVirt/vdsm/pull/37
https://github.com/oVirt/vdsm/pull/33

**Pull request closed without merging**
