### PR TITLE
Revert nmstate bridge options

### PR DESCRIPTION
**Pull request by erav**
Due to the regression in supporting stp priority attribute, we revert using bridge options via nmstate until the regression is fixed.

### CODE REVIEW

**Comment by michalskrivanek** [comment]
please keep 0db3966ccab938cfa67a3f12ec4df78d784619c7 in. I don't want to mess with spec requirements

**Comment by erav** [comment]
> please keep [0db3966](https://github.com/oVirt/vdsm/commit/0db3966ccab938cfa67a3f12ec4df78d784619c7) in. I don't want to mess with spec requirements

done

**Review by mz-pdm — COMMENTED** [review]
Please add the reason the patches are reverted to the commit messages.  Looking up them later on GitHub is difficult.

**Comment by erav** [comment]
> Please add the reason the patches are reverted to the commit messages. Looking up them later on GitHub is difficult.

done

**Review by mz-pdm — DISMISSED** [review]
Thanks.

**Review by mwperina — DISMISSED** [review]
+1

**Review by almusil — APPROVED** [review]

**Pull request merged**
