### PR TITLE
github actions: upgrade to checkout version 3

### PR DESCRIPTION
**Pull request by erav**
Version 2 of the checkout action produces a warning and cancels the action. Upgrading to version 3.

Change-Id: I6f80aeae400104a188615444ca3bdbbcc8817898
Signed-off-by: Eitan Raviv <eraviv@redhat.com>

### CODE REVIEW

**Comment by aesteve-rh** [comment]
Where did you see the warning? I have briefly checked the latest `Actions` and couldn't find it.

**Comment by erav** [comment]
for example here: 
https://github.com/oVirt/vdsm/actions/runs/4154350915

image

**Comment by aesteve-rh** [comment]
There is a warning for the checkout, but it does not seem to cause the Action to cancel. AFAIU seems to be the `podman run` command that fails:
```
Storing signatures
time="2023-02-12T02:50:53Z" level=error msg="Updating image \"44b33053e96b60856ac33e46acff3358db2bdac20da1b5beb0a6dcc9b7a1f0df\" (old names []) failed, deleting it"
time="2023-02-12T02:50:53Z" level=error msg="Error deleting incomplete image \"44b33053e96b60856ac33e46acff3358db2bdac20da1b5beb0a6dcc9b7a1f0df\": identifier is not an image"
Error: 2 errors occurred while pulling:
 * initializing source docker://ovirt/vdsm-network-tests-integration:centos-8: reading manifest centos-8 in docker.io/ovirt/vdsm-network-tests-integration: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

 * committing the finished image: setting names [quay.io/ovirt/vdsm-network-tests-integration:centos-8] on image "44b33053e96b60856ac33e46acff3358db2bdac20da1b5beb0a6dcc9b7a1f0df": layer not known
+ CONTAINER_ID=
```

**Comment by erav** [comment]
added fail-fast:false to network.yml . Functional tests have been having issues since a long time. Solving them on this PR is out of scope and would just delay it indefinitely. So let's merge this PR so the real issues can be addressed more easily

**Review by aesteve-rh — DISMISSED** [review]
There were some concerns in the past regarding the update of the checkout action, but if keeping it outdated raises a problem, I think it is better to update it. Thanks for taking care!

**Comment by erav** [comment]
@sandrobonazzola could you please have a look? Looks like checkout@v3 mutes the warnings which helps in reducing the noise.

**Review by sandrobonazzola — DISMISSED** [review]
LGTM, approving.
I would recomend having a look at https://github.com/oVirt/checkout-action as other repos in oVirt are using it instead

**Comment by erav** [comment]
@sandrobonazzola can you please merge if you approve? I don't have permissions... thanks

**Pull request merged**
