### PR TITLE
Nmstate for bridge options

### PR DESCRIPTION
**Pull request by erav**
continuation of PR #118

### CODE REVIEW

**Comment by almusil** [comment]
Is the package available everywhere? And also this patch should make `network/link/bridge.py` unused, please check it out and if possible create another commit that will remove unused parts of that module.

**Comment by erav** [comment]
passed on network suite el8stream run #42262 with nmstate-1.3.0-1.el8.x86_64

**Comment by erav** [comment]
passed on network suite rhel8 run #42286 with nmstate-1.2.1-3.el8_6.x86_64
passed on basic suite el8s run #42285 with nmstate-1.3.0-1.el8.x86_64

**Comment by erav** [comment]
passed on basic suite rhel8 run #42297 with nmstate-1.2.1-3.el8_6.x86_64

**Review by almusil — APPROVED** [review]

**Pull request merged**
