### PR TITLE
backport: prune bitmaps fix

### PR DESCRIPTION
**Pull request by aesteve-rh**
Commits/PRs cherry picked for backporting (in order):

- https://github.com/oVirt/vdsm/pull/356 (1 commit)
- https://github.com/oVirt/vdsm/pull/354 (3 commits)
- https://github.com/oVirt/vdsm/pull/358 (first commit only, the rest were not relevant)
- https://github.com/oVirt/vdsm/pull/357 (4 commits)

Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)

### CODE REVIEW

**Comment by ahadas** [comment]
@aesteve-rh I see that the first part that is taken from #346 is related to a different bug, https://bugzilla.redhat.com/show_bug.cgi?id=2125290, and seems unrelated to the other changes - shall we clone bz 2125290 to make it visible to QE? where did the issue that it addressed came from (QE/users-list/out test)?

**Comment by ahadas** [comment]
> Appeared in OST run logs, but the error was ignored, and the OST jobs succeeded anyway, so it went unnoticed until logs were inspected.

ack, we had a similar case on ovirt-engine and we backported the fix without having a d/s bug 
I'm not sure if that's the 'right' way to handle it but it looks like we need a d/s bug to raise awareness for these fixes so I filed https://bugzilla.redhat.com/show_bug.cgi?id=2152845
 
> This should have low overall impact, as having a host with no lvm devices is rare. Nonetheless, as we are going to do another build, I thought it may be nice to include.

right, definitely makes sense to include it, the question is how :)
can you please separate that commit out to a different PR that will be attached to https://bugzilla.redhat.com/show_bug.cgi?id=2152845?

**Comment by mz-pdm** [comment]
OK, please add this PR to the bug.

**Comment by aesteve-rh** [comment]
> OK, please add this PR to the bug.

It is already tracked in this bug: https://bugzilla.redhat.com/show_bug.cgi?id=2141371

**Comment by mz-pdm** [comment]
I see, OK.

**Review by mz-pdm — APPROVED** [review]

**Review by ahadas — APPROVED** [review]

**Pull request merged**
