### PR TITLE
The virtual machine XML file mounts glusterfs

### PR DESCRIPTION
**Pull request by xilazz**
Currently virtual machine disk files are mounted via fuse. Can you mount them directly from glusterfs?
Use glusterfs mounting directly as the virt-manager administration tool does :<source protocol='gluster' name='gv1/ centos7.img '>.

### CODE REVIEW

**Comment by mykaul** [comment]
Hi,

1. oVirt uses Gerrit, not github (which is a read-only mirror). Can you send it over there?
2. What exactly are you trying to achieve?

CC @sabose

**Comment by nirs** [comment]
@xilazz, oVirt already support native gluster mounts, but this feature is disabled by default because of incomplete support in libvirt. It may be enabled in the oVirt hyperconverge setup. You can find more info in the RFE[1].

Please use ovirt-users mailing[2] list if you want to get more info on how to use glusterfs. If you want to suggest a change, lets discuss this in ovirt-devel[3] mailing list.

We don't accept patches in github, please see vdsm develpers[4] for more info on how to contribute.

[1] https://bugzilla.redhat.com/1471658
[2] https://lists.ovirt.org/archives/list/users%40ovirt.org/
[3] https://lists.ovirt.org/archives/list/devel%40ovirt.org/
[4] https://www.ovirt.org/develop/developer-guide/vdsm/developers.html

**Comment by xilazz** [comment]
Ok, thank you very much for your reply.
I'm very sorry. I understand how to consult for any further questions. Thanks again.


xilazz@126.com
 
From: Nir Soffer
Date: 2019-06-05 05:07
To: oVirt/vdsm
CC: xilazz; Mention
Subject: Re: [oVirt/vdsm] The virtual machine XML file mounts glusterfs (#14)
@xilazz, oVirt already support native gluster mounts, but this feature is disabled by default because of incomplete support in libvirt. It may be enabled in the oVirt hyperconverge setup. You can find more info in the RFE[1].
Please use ovirt-users mailing[2] list if you want to get more info on how to use glusterfs. If you want to suggest a change, lets discuss this in ovirt-devel[3] mailing list.
We don't accept patches in github, please see vdsm develpers[4] for more info on how to contribute.
[1] https://bugzilla.redhat.com/1471658
[2] https://lists.ovirt.org/archives/list/users%40ovirt.org/
[3] https://lists.ovirt.org/archives/list/devel%40ovirt.org/
[4] https://www.ovirt.org/develop/developer-guide/vdsm/developers.html

**Comment by nirs** [comment]
@xilazz I'm closing this, lets continue in the mailing list.

**Pull request closed without merging**
