### PR TITLE
spec: point to src URL

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Point to the tarball included in the release archive

### CODE REVIEW

**Review by mz-pdm — APPROVED** [review]

**Review by vjuranek — APPROVED** [review]

**Review by tinez — DISMISSED** [review]

**Review by nirs — CHANGES_REQUESTED** [review]
Please rebase on master,  you have a merge commit in your pr, and we don't want them in git history.

**Comment by michalskrivanek** [comment]
so why is squash&merge disabled? that would be easy for the maintainer to do without more ping pong

**Comment by nirs** [comment]
We don’t want to squash patches. We can rebase and merge if needed, but this pr was wrongly updated so it must be pushed again without the merge commit.

**Comment by sandrobonazzola** [comment]
> Please rebase on master, you have a merge commit in your pr, and we don't want them in git history.

Done

**Comment by nirs** [comment]
Thanks @sandrobonazzola!

**Review by nirs — APPROVED** [review]

**Comment by nirs** [comment]
@michalskrivanek we cannot merge this again. Previously vdsm was
configured so we could rebase and merge if needed, but now the
it does not work and we don't have access to the project settings.
This is not productive. We need full access to the project settings.

**Comment by nirs** [comment]
@michalskrivanek found that "rebase" option was hidden in the "update" menu, so we
can handle the rebase issues.

**Pull request merged**
