### PR TITLE
use oVirt's buildcontainer and checkout action

### PR DESCRIPTION
**Pull request by michalskrivanek**

### CODE REVIEW

**Comment by mz-pdm** [comment]
OK, let's use the common container + action and see how it works.

- Please use prefix in the commit message, e.g. "ci: Use oVirt's ...".
- Why to split it to two commits?
- What must be done to change the required checks?

**Comment by michalskrivanek** [comment]
> OK, let's use the common container + action and see how it works.
> 
>     * Please use prefix in the commit message, e.g. "ci: Use oVirt's ...".
> 
>     * Why to split it to two commits?

those were two unrelated changes, one to move to buildcontainer and second to adapt to the new preferred way how to use it
feel free to squash

>     * What must be done to change the required checks?

reconfigure in github project settings

**Comment by michalskrivanek** [comment]
@mz-pdm done

**Review by mz-pdm — APPROVED** [review]

**Comment by mz-pdm** [comment]
IIRC there were two concerns raised:

- Whether everything will work with the container.  The easiest way to get know is to merge the PR.

- How much time it takes to fetch the big container.  Probably not a big problem.

If you disagree or have other concerns, please speak up, otherwise I'll merge it.  3, 2, 1, ...

**Comment by aesteve-rh** [comment]
Looks good to me, but required checks need to be updated before integrating.

**Comment by michalskrivanek** [comment]
> Looks good to me, but required checks need to be updated before integrating.

let me do that. the other PRs will start complaining until merged, though

**Comment by michalskrivanek** [comment]
> > Looks good to me, but required checks need to be updated before integrating.
> 
> let me do that. the other PRs will start complaining until merged, though

done

**Pull request merged**
